---
- name: Install and configure Zabbix proxy
  hosts: zabbix_proxy

  tasks:
    - include: tasks/mysql_server.yml

    - include: tasks/zabbix_repo.yml
    - include: tasks/zabbix_proxy.yml

  handlers:
    - include: handlers/mysql_service.yml
    - include: handlers/zabbix_proxy.yml
