---
- name: Install MySQL server
  become: true
  apt: name=mysql-server,python-mysqldb,python-apt,curl state=present
  register: mysql_install

- name: install mysql-server
  become: true
  apt: name=mysql-server state=present update_cache=yes

- name: ensure mysql started
  become: true
  service: name=mysql state=started enabled=yes

## jsh: final ops version may want to modify this and lock it down ...
- name: ensure mysql is listening on all ports
  become: true
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
              line="bind-address = 0.0.0.0"
  notify: mysql_restart

- name: Start MySQL server
  become: true
  service: name=mysql state=started enabled=yes
  when: mysql_install is defined and mysql_install.changed
